services:
  - type: web
    name: solupi-backend
    env: docker
    region: ohio
    plan: free
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 3001
      - key: DATABASE_URL
        sync: false
      - key: SOLANA_RPC_URL
        sync: false
